### ISSUE TITLE
Reunión 1

### ISSUE THREAD

**Issue by lauverrec** [InnosoftDaysPresidencia/Igualdad#2]
Esta fue la primera reunión que mantuvimos para conocernos y empezar a trabajar.

**Comment by MariaRuizGutierrez** [comment]
7a799a7eafd942c03e17051cd434c5f16e6e0d34 esta es la evidencia de Laura
676fc03f44f17682adcf2c7c084ec405fe945d91 esta es la evidencia de María
793eb7d755afe5c291f4aaac78faf0a0c4429ed1 esta es la evidencia de Feliciano
793eb7d755afe5c291f4aaac78faf0a0c4429ed1 esta es la evidencia de José Félix
